services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.web
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery:
    build:
      context: .
      dockerfile: backend/Dockerfile.celery
    depends_on:
      - backend
      - redis
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
